### PR TITLE
standardize the media control creation for external and default

### PR DESCRIPTION
**Pull request by 3dd13**
call render() for both external and default media control

### CODE REVIEW

**Comment by flavioribeiro** [comment]
LGTM

**Comment by flavioribeiro** [comment]
Can you remove the generated files (clappr.js, clappr.min and clappr.map)?

**Comment by leandromoreira** [comment]
good but remove the files @flavioribeiro listed

**Comment by 3dd13** [comment]
@flavioribeiro @leandromoreira 
pushed another commit with previous versions of the dist files

**Comment by leandromoreira** [comment]
LGTM @towerz

**Pull request merged**
