### PR TITLE
Suggested Fix: onReady event firing with m3u8

### PR DESCRIPTION
**Pull request by wahajdar**
Suggested fix for #1563

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thanks, @wahajdar did you see the errors on [CI](https://travis-ci.org/clappr/clappr/builds/344230077?utm_source=github_status&utm_medium=notification)?

**Comment by wahajdar** [comment]
Apologies, let me consider. 
Thanks @leandromoreira

**Comment by wahajdar** [comment]
@leandromoreira , can you please guide me how could I fix coverage check.
Will be grateful, thanks

**Comment by towerz** [comment]
@wahajdar Thanks, this is a great addition. The ready event should be reliable to allow code to run as soon as the playback can accept calls. Otherwise, we could end with a number of issues or messy code handling different types of playbacks.

About the code coverage, don't worry for now. @joaopaulovieira is working on a test framework change we want to do so just not breaking the current tests is ok.

I'm working on an FSM implementation for the base playback, in order to allow all the playbacks to share the same state semantic. Basically, the playbacks will all implement the state machine described [here](https://github.com/clappr/clappr-docs/wiki/Architecture#playback)

**Comment by wahajdar** [comment]
@towerz thank you for letting me contribute. Thanks for clarifying certain things here, will follow clappr architecture docs for better understanding.

**Comment by poshe** [comment]
class **HLS** extends **HTML5VideoPlayback** and they both have the same `_ready()` function and they both call it in their `render()` functions. Is that OK?

**Pull request merged**
