### PR TITLE
docs: update readme and add player error documentation

### PR DESCRIPTION
**Pull request by kslimani**
I started some player fatal error handling documentation.

~~I am waiting for playback issue to be resolved (@thiagopnts is on it), i will add another example using a custom error playback to display an simple error page.~~

_DISCLAIMER: i am a bad english writer, it may contains typos 😃_

### CODE REVIEW

**Comment by kslimani** [comment]
Added another example which should satisfy #1381 @Niko78 issue.

**Comment by leandromoreira** [comment]
Great, thank you very much @kslimani  you're doing such a great work!!

**Comment by leandromoreira** [comment]
can we merge this?

**Comment by kslimani** [comment]
@leandromoreira unless someone think it miss something or there are typos, yep 👍

**Pull request merged**
