### PR TITLE
playbackNotSupportedMessage: center text when only one line long (fixes #768)

### LINKED ISSUE #768: playbackNotSupportedMessage is not centered if text is one line long
Browser: Chrome 47.0.2526.106 m, Firefox 42.0, Microsoft Edge 20.10240.163840.0, IE 11.0.10240.16603

OS: Windows 10

Clappr Version: 0.2.29

Steps to reproduce:

Add playbackNotSupportedMessage: 'Please try on a different browser' to constructor
Load page with invalid source to force error message
I was expecting centered text but instead it shows left justified text

centered
not centered

### PR DESCRIPTION
**Pull request by hounvs**
I'm not sure if this is the correct solution. Worked for me on all browsers that I initially had the issue on though. Seems to work. Someone more experienced double check it please haha

### CODE REVIEW

**Comment by hounvs** [comment]
For Issue clappr#768

**Comment by leandromoreira** [comment]
Also, please try to test it with:

* Chrome
* Firefox
* IE
* Edge
* Safari

* IOs 
* Android FF
* Android Chrome

To see if this doesn't break anything. There are several services for this like https://www.browserling.com/

**Comment by leandromoreira** [comment]
@hounvs please take a look at @tjenkinson suggestion also can you squash your commits into one. :) don't be afraid to ask for help.

**Comment by hounvs** [comment]
Sorry for the late response. I'll look into it tonight. I knew there had to be a better way

**Comment by leandromoreira** [comment]
Thanks @hounvs :+:

**Comment by hounvs** [comment]
@leandromoreira I think I did it correctly. I've never squashed before and it took a few hours of manually fixing conflicts from every commit that was in any of the merge updates from clappr/master. Was there something I was doing wrong? I'm new to git but it seems odd that I had to resolve old conflicts

**Comment by leandromoreira** [comment]
Thanks @hounvs yeah git sometimes can give you a hard time. I just asked you to squash because we usually make each commit atomic, like each commit do a single thing and your PR had many commits to do the same. :)

Once again thank you very much, 

When I was learning git this helped me a lot https://codewords.recurse.com/issues/two/git-from-the-inside-out also about squash this one can help too https://www.youtube.com/watch?v=qh9KtjfjzCU

**Pull request merged**
