### PR TITLE
trigger Events.PLAYBACK_ERROR on networkError

### PR DESCRIPTION
**Pull request by PNixx**

### CODE REVIEW

**Comment by flavioribeiro** [comment]
Thanks @PNixx!

**Comment by leandromoreira** [comment]
Thanks @PNixx and @flavioribeiro I think that the best way to fix this issue is triggering `PLAYBACK_ERROR` only after reaching the max numbers of attempt. With the solution we'd drop the recovering tries.


Do you agree?

```javascript
  onError(evt, data) {
    if (data && data.fatal && this.recoverAttemptsRemaining > 0) {
      this.recoverAttemptsRemaining -= 1
      switch (data.type) {
        case HLSJS.ErrorTypes.NETWORK_ERROR:
          Log.warn(`hlsjs: trying to recover from network error, evt ${evt}, data ${data} `)
          this.hls.startLoad()
          break
        case HLSJS.ErrorTypes.MEDIA_ERROR:
          Log.warn(`hlsjs: trying to recover from media error, evt ${evt}, data ${data} `)
          this.recover()
          break
        default:
          Log.error(`hlsjs: trying to recover from media error, evt ${evt}, data ${data} `)
          this.trigger(Events.PLAYBACK_ERROR, `hlsjs: could not recover from error, evt ${evt}, data ${data} `, this.name)
          break
      }
    } else {
        this.trigger(Events.PLAYBACK_ERROR, `hlsjs: could not recover from error after maximum number of attempts, evt ${evt}, data ${data} `, this.name)
    }
  }
```

**Comment by leandromoreira** [comment]
We're going to release a version of Clappr therefore we'll need to rollback this commit, I'm sorry. :( But on  the other hand we're going to fix the issue :)

**Comment by towerz** [comment]
I agree with @leandromoreira, triggering an error event should only occur when there's no more recovery attempts left.

**Pull request merged**
