### PR TITLE
#373 Fix play icon height with player height percents

### PR DESCRIPTION
**Pull request by irongomme**
I think $el.height() is enough and make percent height for the player able to display the big play button in a good height

### CODE REVIEW

**Comment by irongomme** [comment]
Need a fix for resize play button on player resize

**Comment by thiagopnts** [comment]
Actually this is related to using percentage as height/width, which we don't support

**Comment by irongomme** [comment]
@thiagopnts Do you plan to support it ?

**Comment by thiagopnts** [comment]
@irongomme Not right now. The internal parts of the player currently depends on a fixed height/width from its "root" element. I would suggest you to manually set the player's height/width using the `.resize({width: width, height: height})` method from the player instance as you need.

**Pull request merged**
