### PR TITLE
Several enhancements in Player class

### LINKED ISSUE #677: player.setVolume() does not updates the localStorage value
On http://cdn.clappr.io/ website in console enter
```js
localStorage
```
This will return the
```json
{clappr.cdn.clappr.io.volume: "0"}
```
then enter
```js
player.setVolume(50);
```
and then again
```js
localStorage;
```
but if the volume is changed by pressing on volume control bar then localStorage returns
```json
{clappr.cdn.clappr.io.volume: "56.02678571428571"}
```

### PR DESCRIPTION
**Pull request by gamtiq**
I have made the following improvements in Player class:
* refactored `setVolume` and `getVolume` methods (this change should fix #677)
* changed implementation of `mute` and `unmute` methods to restore volume level
* added `start` method
* added `return this;` into interface methods so that make them chainable

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thank you so much @gamtiq 

@clappr/core any thoughts? 

- some fixes (great)
- returning player itself (I'm okay with this, we already adopted that for render)
- adding a new start method (this is where I need to think better, it is not feasible to mobile, at least in the first play)

**Comment by towerz** [comment]
@leandromoreira I agree with you. Perhaps the `start` method should be analyzed more carefully.

We should consider moving these changes into the configure and load methods, instead of creating a new one that decides either reconfiguring or loading a new source based on the type of its parameters.

**Comment by gamtiq** [comment]
I have added `start` method for convenience so that to make just one call instead of two (`load`/`configure` and `play`) when starting playing of new video.
Maybe it is worth not to add new method but change implementation of `play` method so that it would be possible to pass optional parameters specifying source that should be played.
If that is accepted I can delete `start` method and move the appropriate logic into `play` method.

**Comment by towerz** [comment]
@gamtiq I was actually more inclined to add these changes you made on `start` to the `load`/`configure` methods. I understand you intended to automatically start the video on load when calling the `start` method.

Instead of doing that, I suggest to use the `autoPlay` semantics when calling `load`/`configure`. On `load`, we could add an `autoPlay` parameter to automatically start the video, and when `configure` is called, setting the `autoPlay` flag to true, the video would start, just like if you have called `play` afterwards.

**Comment by gamtiq** [comment]
I agree with you. Indeed adding auto play ability for `load` method would be enough.
Should I make any additional changes in my pull request? Or do you plan to merge only necessary commits (excepting c594318)?

**Comment by towerz** [comment]
It's up to you. Do you prefer implementing the additional changes yourself and adding to the PR or would you like us to merge the other commits except c594318?

**Comment by gamtiq** [comment]
I can make additional changes in PR. If I correctly understand you, it is necessary only to add the third parameter for `load` method and to modify the method slightly. I will do it.

**Comment by towerz** [comment]
Great job, thanks @gamtiq! 🍻

**Pull request merged**
