### PR TITLE
Fix Html5Video autoplay after playback destroyed

### LINKED ISSUE #1211: Video continue playing after paused.
Chrome 54.0.2840.71 (64-bit)
MAC OS 10.12.1
Clappr: 0.2.62, 0.2.63 and 0.2.64

**Steps to reproduce**:
Init the object with _two_ sources in the array, the first is RMTP and second is HLS.
`new Clappr.Player({ sources: [theFirstOne, theSecondOne})`

* Steps
Init the player and wait it start to play (RMTP setup)
Pause the video.
The video is paused but in the background is still playing (It's possible to listen the audio)
It's possible to listen the two audios, RMTP and HLS streaming.

I took a look in the source code:
`clappr/src/playbacks/html5_video/html5_video.js`

And the following commit:
https://github.com/clappr/clappr/commit/3140ce09b5279f180d688c25447ef9220f74d9aa#diff-2c2c8cae7099c541811236d5f7c5d53d

Reported here: 
`https://github.com/clappr/clappr/issues/1076`

And this line introduced the bug:
`this.options.autoPlay && process.nextTick(() => this.play())`

But the old line works perfectly:
`this.options.autoPlay && this.play()`

Possible solution:
I suspect calling `this.play()` async cause some double play.
I still don't understand why It's playing two videos at the same time, one RMTP and the other HLS.

Maybe the sources should not contain two or more different kind (RMTP and HLS) or this is not the case?

### PR DESCRIPTION
**Pull request by tjenkinson**
Fixes #1211 

(Untested)

### CODE REVIEW

**Comment by leandromoreira** [comment]
@kolpax can you test it?

**Comment by kafeltz** [comment]
I tested the pull-request and it did work for me.
Thx.

**Comment by gfronza** [comment]
@leandromoreira @tjenkinson is there a timetable for merging and releasing this one? :)

**Comment by leandromoreira** [comment]
@gfronza soon !

**Comment by towerz** [comment]
Thanks @tjenkinson! :beers:

**Pull request merged**
