### PR TITLE
Added support for ES6 methods for older browsers

### PR DESCRIPTION
**Pull request by michaelcunningham19**
This PR fixes the error:

```
 %c[error]color: #ff0000;font-weight: bold; font-size: 13px;error on eventcore:containers:createdtrigger-TypeError: Object doesn't support property or method 'find' 
```

Which occurs on any browser which does not support the native ES6 method 'find' on the Array prototype object. (IE10 and IE11 for example)

Adding the official _babel-polyfill_ package solves this from occurring.

See more info: https://github.com/clappr/clappr/issues/788

### CODE REVIEW

**Comment by michaelcunningham19** [comment]
@tjenkinson 

It polyfills the methods in the user's browsers.

I agree it would be nice to have it handled in the build process, but following the official usage instructions it says to simply 'require/import' at the top of the main entry point.

**Comment by leandromoreira** [comment]
Thanks :) @michaelcunningham19

Can you remove `dist/` from your commits?

We @clappr/core also need to check the final weight added by this polyfill, maybe it's easier to use `https://lodash.com/docs#find` (that we already have) or even to provide a pollyfill using this or yet use the [mozilla polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

**Comment by leandromoreira** [comment]
I prefer to fix this instead of adding another dependency at `src/plugins/sources.js`

```diff
+import find from 'lodash.find'

-var firstValidSource = this.core.containers.find((container) => container.playback.name !== 'no_op') || this.core.containers[0]
+var firstValidSource = find(this.core.containers((container) => container.playback.name !== 'no_op') || this.core.containers[0]
```

What do you think?

**Comment by michaelcunningham19** [comment]
@leandromoreira 
That's a good catch, I didn't think of using lodash.find here!

I switched it up to use that instead rather than the polyfill.

@tjenkinson 
IE10 doesn't support any ES6 features as far as I know, so there could be more things like this pop up in the future, but for now I agree with not bringing in another dependency.

**Comment by leandromoreira** [comment]
@michaelcunningham19 do another PR fixing the find with load.find :)

**Pull request closed without merging**
