### PR TITLE
Allow source to be a an instance of a class

### PR DESCRIPTION
**Pull request by tjenkinson**
useful for cases like https://github.com/tjenkinson/clappr-videocontext-playback

### CODE REVIEW

**Comment by towerz** [comment]
LGTM

**Comment by thiagopnts** [comment]
wouldn't be easier to pass the instance as a parameter for the new playback? seems weird to have the core source support other things than strings

**Comment by leandromoreira** [comment]
@thiagopnts do you mean?

```javascript
var _player = new Clappr.Player({sourceSolver: MyInstance})
```

**Comment by thiagopnts** [comment]
your canplay method can use information from the source string to decide rather it should play or not, e.g. in the 360 plugin I just pass `video.mp4#360` as a source and my `canPlay` just match for `/#360$/`.

**Comment by thiagopnts** [comment]
@tjenkinson would it work with something like this?

```javascript
constructor(options) {
    super(options)
    this._context = options.context
  //etc
 }
VideoContextPlayback.canPlay = (resource) => {
  return resource === 'video-context-playback'
}
```

**Comment by thiagopnts** [comment]
aren't params from the player constructor passed to the other components anymore?

**Comment by thiagopnts** [comment]
agree, I would just avoid adding code for edge cases that can be worked around using the plugin system

**Pull request merged**
