### PR TITLE
adds hasEnded() method to playbacks, container, and player

### PR DESCRIPTION
**Pull request by tjenkinson**
Tested in Chrome with `Html5Video`, `FlasHLS` and `HLS` playbacks.

### CODE REVIEW

**Comment by leandromoreira** [comment]
I'm in favor of another property (like we did for ready) or we should change everything to methods :P what do you think @clappr/core ?

```javascript
get ended() {  return this._ended }
//or
isEnded() { return this._ended }
```

I vote in favor of property because the states (ready, ended, paused ...) sound more like a property than a method/function.

**Comment by flavioribeiro** [comment]
just curious about the use case of this method, why not listen to `PLAYBACK_ENDED`?

**Comment by leandromoreira** [comment]
@clappr/core are we going to use `attribute` or `method` to cover this ? **hasEnded** (or ended)

**Comment by leandromoreira** [comment]
Cool @tjenkinson are you going to rebase or do another PR for `ended` instead of `hasEnded()`

**Comment by leandromoreira** [comment]
I'll close, thanks once more :)

**Pull request closed without merging**
