### PR TITLE
utils: added days to formatTime

### PR DESCRIPTION
**Pull request by derrod**
This time a pull request without issues...

### CODE REVIEW

**Comment by leandromoreira** [comment]
@derrod you just missed your tests cases.

**Comment by derrod** [comment]
God damn it.

**Comment by leandromoreira** [comment]
:beers: @derrod thanks man :)

**Comment by derrod** [comment]
@leandromoreira I added the test back again (it's a seperate commit though).

**Comment by leandromoreira** [comment]
@derrod LGTM, thanks! @flavioribeiro do you think this is valid ? ( I mean, seeking for days )

**Pull request merged**
