### PR TITLE
Check if fullscreen supported on <video /> if other fullscreen checks fail

### LINKED ISSUE #1127: Fullscreen option is not available on iPad
**Browser**: Safari for iOS 9.3

**OS**: iOS 9.3

**Clappr Version**: 0.2.25

**Steps to reproduce**:
* open cdn.clappr.io on iPad
* play video
* observe that media control does not have the fullscreen button

**Did you try to reproduce this issue at http://cdn.clappr.io/**
Yes

**Other Notes**
It looks like `document.webkitFullscreenEnabled` is not available on Safari for iOS.  However, fullscreen capabilities do exist.

Note that you can double-tap the video to have it go fullscreen still.

The fullscreenEnabled check that works for iOS Safari would have to wait for the media to load, and then look at `videoElement.webkitSupportsFullscreen` (which is not available until the media is loaded)

https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html

### PR DESCRIPTION
**Pull request by tjenkinson**
This is required for iOS
fixes #1127

### CODE REVIEW

**Comment by leandromoreira** [comment]
lgtm

**Comment by bikegriffith** [comment]
Per my comment in the issue, this solves the original problem. Tested on an iPad Air and iPad 2 with iOS 9.3

**Comment by leandromoreira** [comment]
LGTM @clappr/core thoughts?

**Comment by leandromoreira** [comment]
Thanks mister @tjenkinson lol

**Pull request merged**
