### PR TITLE
update release process to deploy only the dist directory

### PR DESCRIPTION
**Pull request by jfairley**
This changes the npm release process to deploy only the `dist` directory rather than the entire repo, as suggested [in #793](https://github.com/clappr/clappr/issues/793#issuecomment-179400290).

__This would do two things:__

1. Removes the unnecessary "npm install" that runs on a client machine when clappr is declared as a dependency. This speeds up user install time, as well as gets around the issue I brought up in #793.
1. Reduces the overall size of the package distributed to NPM (speeding up user download time).

If someone wants to run tests or make a custom build, they can always clone the repo. IMO, it's strange to do this inside `node_modules/clappr` anyway.

__What did I change?__

1. Copy `package.json` into `dist` and slim it down by removing "dependencies" and "devDependencies".
1. Update the `bump` script to version `dist/package.json` and publish from the `dist` directory.
1. Update `webpack.config.js` to not remove `dist/package.json` when it does the "clean".
1. Removed `.npmigore`, because it is no longer needed.

<br>

Lemme know what you think.

### CODE REVIEW

**Comment by jfairley** [comment]
Coverage dropped with config changes. That's one reason I stopped using coveralls. :wink:

**Comment by jfairley** [comment]
BTW, I don't know what you bower release process looks like, and I'm not familiar with "yuidoc", so let me know if I can update this to better support those libraries.

**Comment by leandromoreira** [comment]
What do you think about this @towerz and @tjenkinson ?

**Comment by towerz** [comment]
I would hold this change for a while. I already had a discussion with someone about this, I can't remember exactly who/when. The problem with publishing only the dist folder is that when someone uses webpack or babel in his project, we'll be forcing them to use the compiled version of clappr. Installing only the dist files is only recommended if you are publishing a library which should not be bundled into someone's code or have its inner workings exposed.

I've seen packages distributed just the way we do as well as packages that only include the compiled files in their distribution. Since the beginning we wanted the user to either build clappr into their own product as well as use clappr by itself with no changes. The way we distribute clappr files on npm supports both ways. One of the biggest problems this change will introduce is that the players that include clappr into their own compiled bundle may have some compilation issues introduced (for example, many objects that aren't exported but could be customized), as well as duplicating babel's ES6 runtime, and resuting in an unoptimized bundle, since the entire clappr bundle, with it's own UMD module exports will be bundled into another UMD module.

**Comment by jfairley** [comment]
@towerz I can't say I'm familiar with the types of potential issues you sound familiar with. If you choose to not merge, I understand. 

I do hope you give some thought to #793, however. Your use of shrinkwrap forces me to have a preinstall script to remove it so I can build in linux. Alternatively, I know I can use node 5, but my dependency graph is all sorts of busted in npm 3, so that's not something I can easily jump into unfortunately.

**Comment by leandromoreira** [comment]
hey @jfairley since we removed the shoryuken can we close this ?

**Comment by jfairley** [comment]
https://github.com/clappr/clappr/pull/866 solves my immediate issue. Fine to close.

**Pull request closed without merging**
