### PR TITLE
mute or unmute video on volume change (muted autostart on mobile devices)

### LINKED ISSUE #1314: Revisit autoplay on iOS
Previous wonfix: #404 

Please see: https://webkit.org/blog/6784/new-video-policies-for-ios/ (circa July, 2016)

Now that iOS 10 Safari relaxed `autoplay` policy per above blog post, how about we make clappr also autoplayable on iOS 10 Safari.

I have noticed that clappr does not use `<video>` tag for HLS on iOS 10 Safari. If we were to make clappr autoplayable on iOS 10 Safari, does it entail some major code change?

I'm ready to commit some time to knock this one off. If anyone could give some higher level overview, I might be able to get something going. Unless... it is already supported. (I was using clappr `0.2.65` on iOS 10.2.1 Safari with HLS, clappr did not autoplay.)

### PR DESCRIPTION
**Pull request by kslimani**
These changes allow autoplay on mobile devices when `mute` player option is set to true. (_and playback `playInline` is set to true on iOS_).

Thank you to @tomas2387 for original pull request #1260.

Example usage :

```javascript
var player = new Clappr.Player({
  parentId: '#player-wrapper',
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  autoPlay: true,
  playback: { playInline: true }, // Required only by iOS
  height: 360,
  width: 640
});
```

Requirements :

* iOS version >= 10
* Android with Chrome version >= 53

supersede #1260, should fixes #1314

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thank you @kslimani  🍰

**Comment by kslimani** [comment]
BTW, note it seems to not work with HLS source. I will investigate why.

**Comment by kslimani** [comment]
Added a fix for HLS source on mobile devices.

**Comment by leandromoreira** [comment]
@kslimani you rock! 🚀

**Pull request merged**
