### PR TITLE
updates to send data to coveralls

### PR DESCRIPTION
**Pull request by leandromoreira**

### CODE REVIEW

**Comment by jfairley** [comment]
Just a 2-cents here... I tried out coveralls, but hated the UX, so I switched our projects to https://codecov.io/. I'm much happier looking at that site. :grin: Try it out if you get a chance.

**Comment by leandromoreira** [comment]
@jfairley can you give me any project where I can see that UX? (I tried to find on google but none show up :( )

**Comment by jfairley** [comment]
Yeah googling was difficult for me too... I had only found this one before I got tired of hitting "next"
https://codecov.io/github/audreyr/cookiecutter

I messaged them and got these links.
https://codecov.io/github/pyca
https://codecov.io/github/spotify
https://codecov.io/github/shopify
https://codecov.io/github/docker

**Comment by leandromoreira** [comment]
Thanks :) I'm gonna see them

**Comment by jfairley** [comment]
Cool. I use the service for both Java and JavaScript (Node, Angular, and React). My projects are all private, but I can still help set up if you need.

**Comment by leandromoreira** [comment]
are you using ec6?

**Comment by jfairley** [comment]
_ES6_? yes

**Pull request merged**
