### PR TITLE
adds support for hls.6.x

### PR DESCRIPTION
**Pull request by leandromoreira**
To fix https://github.com/clappr/clappr/pull/1191#event-845886043 and https://github.com/clappr/clappr/issues/1143#issuecomment-246997927

### CODE REVIEW

**Comment by leandromoreira** [comment]
Although the build says it's broken bc of lint I can't reproduce it locally.

```
$ npm run lint

> clappr@0.2.63 lint /Users/leandro.moreira/src/clappr
> eslint src/ test/
```

**Comment by kslimani** [comment]
It is hls.js line 358 : https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L358

**Comment by leandromoreira** [comment]
@kslimani if you try to run it locally it doesn't show the lint error ;(

**Comment by kslimani** [comment]
it should be 

```javascript
  _fillLevels() {
    this._levels = this._hls.levels.map((level, index) => {
      return {id: index, level: level, label: `${level.bitrate/1000}Kbps`}
    })
    this.trigger(Events.PLAYBACK_LEVELS_AVAILABLE, this._levels)
  }
```

**Comment by kslimani** [comment]
Locally, i have the following message

```
/home/kslimani/projects/clappr/src/playbacks/hls/hls.js
  358:5  error  Expected indentation of 6 spaces but found 4  indent

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kslimani** [comment]
Additionally, if i try to build Clappr with current master, hls.js playback doesn't work anymore. (but maybe you are already aware of issue ?). I am still digging where is the problem, if i findout something i will update.

**Comment by leandromoreira** [comment]
@kslimani can you test this on your side? I already ran some tests (mp4, hls).

**Comment by kslimani** [comment]
@leandromoreira yes i am gonna test and feedback.

**Comment by kslimani** [comment]
@leandromoreira so far it is working again (testing with "npm run start" build demo page). :+1:

**Comment by leandromoreira** [comment]
thank you very much @kslimani

**Comment by leandromoreira** [comment]
> I think some people might be setting hlsjs options and accessing the hlsjs instance directly and this might cause problems for them?

I think these people are relying on unstable abstraction :P I'm in favor of keeping the current minor version.

**Comment by shacharz** [comment]
> unstable abstraction

What abstraction are you referring to?

**Comment by leandromoreira** [comment]
> What abstraction are you referring to?

@shacharz I was referring to the people that use the private instance of `hls` (`clapprInstance.core.getCurrentPlayback()._hls`) as something stable

**Comment by shaharmor** [comment]
@leandromoreira what about people that used a custom XHR loader for hls.js that was passed using Clappr's config? This update broke it for them because hls.js 0.6.x has a different API for its xhr loader.

**Comment by leandromoreira** [comment]
@shaharmor that's something we need to fix :) btw feel free to do a PR!

**Comment by shacharz** [comment]
@leandromoreira I don't mind doing a PR, but we need to agree about it first :)
The 2 solutions I see:
1. revert to previous hls.js
2. release a major version and remove 0.2.64

**Comment by leandromoreira** [comment]
oh so the new HLS doesn't offer `XHR loader` config?

**Comment by shacharz** [comment]
@leandromoreira It does, but the API between the XHR loader and the rest of the library has changed

**Comment by leandromoreira** [comment]
So it might be better to offer this new API or if possible to adapt both new and old clients.

**Pull request merged**
