### PR TITLE
Remove shrinkwrap

### PR DESCRIPTION
**Pull request by tjenkinson**
See https://github.com/clappr/clappr/issues/793 for info.
(Closes https://github.com/clappr/clappr/issues/793)

### CODE REVIEW

**Comment by leandromoreira** [comment]
shouldn't we use another thing in place of shrinkwrap?

**Comment by leandromoreira** [comment]
I'm with @tjenkinson can we merge this PR @clappr/core ?

**Comment by towerz** [comment]
@leandromoreira that's fine by me

**Comment by leandromoreira** [comment]
once again thanks mister @tjenkinson  :smile:

**Comment by jfairley** [comment]
:+1: thanks @tjenkinson

**Pull request merged**
